public with sharing class ContainerHelper {
    
    public static final String STATUS_DELIVERY_ARRIVED = 'Arrived for delivery';
    public static final String STATUS_DELIVERY_WAITING = 'Waiting for delivery';
    public static final String STATUS_DELIVERED = 'Delivered';
    public static final String STATUS_LOAD_ARRIVED = 'Arrived for loading';
    public static final String STATUS_LOAD_WAITING = 'Waiting for loading';
    public static final String STATUS_LOADED = 'Loaded';

    public static final String ACTION_ARRIVED = 'Arrived';
    public static final String ACTION_DELIVERED = 'Delivered';
    public static final String ACTION_RELOCATED = 'Relocated';
    public static final String ACTION_LOADED = 'Loaded';


}